### TODO
1. Softmax layer
2. Fix backprop
3. Gradient checking
4. Visualize loss
5. Embeddings
6. Gradient of cross ent

In [1]:
import config
import argparse
import random
import networkx as nx
import numpy as np
from collections import defaultdict
from pyvis.network import Network
import matplotlib.pyplot as plt
from networkx.algorithms.community.modularity_max import greedy_modularity_communities

In [2]:
seed = 100
np.random.seed(seed)

### Graph data

In [3]:
G = nx.karate_club_graph()

In [4]:
G.number_of_nodes(), G.number_of_edges()

(34, 78)

### Generate labels from communities

In [5]:
communities = greedy_modularity_communities(G)
colors = np.zeros(G.number_of_nodes())
classes = set()

for i, c in enumerate(communities):
    colors[list(c)] = i
    classes.add(i)
    
num_classes = len(classes)
labels = np.eye(len(classes))[colors.astype(int)]

### Color nodes

In [6]:
def random_color():
    return '#%02X%02X%02X' % (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))

# uncomment for random colors
# color_map = {cls: random_color() for cls in classes}
color_map = {0: '#46FB47', 1: '#B9E6B5', 2: '#9F9EBF'}

colored_graph = Network(width='100%', notebook=True)

for node in G.nodes():
    colored_graph.add_node(node, color=color_map[int(colors[node])])
    
for edge in G.edges():
    colored_graph.add_edge(int(edge[0]), int(edge[1]))
    
colored_graph.show('colored_graph.html')

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


In [7]:
def renormalization(G):
    A = nx.to_numpy_matrix(G)
    I = np.eye(len(A))
    A_tilde = A + I
    D_tilde = np.zeros(A.shape, int)
    np.fill_diagonal(D_tilde, np.sum(A_tilde, axis=1).flatten())
    D_tilde = np.linalg.inv(D_tilde)
    D_tilde = np.power(D_tilde, 0.5)
    return D_tilde @ A_tilde @ D_tilde

In [8]:
nx.to_numpy_matrix(G)

matrix([[0., 4., 5., ..., 2., 0., 0.],
        [4., 0., 6., ..., 0., 0., 0.],
        [5., 6., 0., ..., 0., 2., 0.],
        ...,
        [2., 0., 0., ..., 0., 4., 4.],
        [0., 0., 2., ..., 4., 0., 5.],
        [0., 0., 0., ..., 4., 5., 0.]])

In [9]:
A_hat = renormalization(G)
print(A_hat)

[[0.02325581 0.11136921 0.13076645 ... 0.06502561 0.         0.        ]
 [0.11136921 0.03333333 0.18786729 ... 0.         0.         0.        ]
 [0.13076645 0.18786729 0.02941176 ... 0.         0.0549235  0.        ]
 ...
 [0.06502561 0.         0.         ... 0.04545455 0.13655775 0.12182898]
 [0.         0.         0.0549235  ... 0.13655775 0.02564103 0.11437725]
 [0.         0.         0.         ... 0.12182898 0.11437725 0.02040816]]


### Helper functions

In [10]:
def glorot_init(in_dim, out_dim):
    sd = np.sqrt(6.0 / (in_dim + out_dim))
    return np.random.uniform(-sd, sd, size=(in_dim, out_dim))

### Gradient Descent

For each iteration of gradient descent, compute local gradients with **backpropagation** - compute global gradient as a chain of local gradients using chain rule of calculus.

Starting from the last layer $l$:

$$
\delta^{(l)}=\frac{\partial}{\partial z^{(l)}}\mathcal{L}
$$

Think of the **error signal** $\delta^{(l)}$ as serving as the same function as $x$ during the forward pass.

For layer $i$ in $l-1$ to $2$:

$$
\begin{align*}
    \nabla_{w^{(i)}}\mathcal{L}&=\delta^{(i+1)}a^{(i-1)^{\top}}&&\quad a^{(i-1)}\text{ is the incoming activation to layer } i \text{ from layer }i-1\\\\
    \nabla_{b^{(i)}}\mathcal{L}&=\delta^{(i+1)}&&\quad\text{shift by error signal}\\\\  
    \delta^{i} &= W^{i^{\top}}\delta^{i+1}\odot\frac{\partial}{\partial z}f(z^{(i-1)})&&\quad W^{i^{\top}} \text{ propagates the error signal backwards as a linear combination scaled by the derivative}
\end{align*}
$$

Think about the convexity of the latent space as discretized across dimensions of $z\in\mathbb{R}^{N}$. Each row of a hidden layer corresponds to a neuron, which corresponds to a position in the activation vector for a given input vector. As $\frac{\partial}{\partial z}f(z)\rightarrow 0$, for the particular combination of activations given to this neuron from the previous layer, the derivative indicates how this specific neuron is changing - which measures the convexity of this particular dimension in latent space $\mathbb{R}^{N}$.

As $\frac{\partial}{\partial z}f(z)\rightarrow 0$, the neuron reacts less to the incoming linear combination, which means that for this combination of features, there is a local minima in this latent space. So as backpropagation progresses across training, gradients of neurons converge to local minima.

For each layer $i$, apply gradient descent:

$$
\begin{align}
    W^{(i)} &= W^{(i)} - \alpha\mathbb{E}[\nabla_{W^{(i)}}\mathcal{L}]\\
    b^{(i)} &= b^{(i)} - \alpha\mathbb{E}[\nabla_{b^{(i)}}\mathcal{L}]
\end{align}
$$

$$
\mathbb{E}[\nabla_{W_{j}}]=\frac{1}{b}\sum^{b}_{j=1}\nabla_{W_{j}}\mathcal{L} \text{ is the expected gradient of the batch of samples and same for bias}
$$

In [11]:
class GradientDescent(object):
    def __init__(self, parameters, learning_rate):
        self.parameters = parameters
        self.learning_rate = learning_rate
        
        
    def zero_gradients(self):
        for layer in self.parameters:
            layer.W_grad = np.zeros(layer.W.shape)
            layer.b_grad = np.zeros(layer.b.shape)
    
    
    def step(self):
        for layer in self.parameters:
            layer.W -= self.learning_rate * layer.W_grad
            layer.b -= self.learning_rate * layer.b_grad

### Graph Convolutional Layer

$$
\text{ReLU}(\hat{A}XW^{1}+b^{1})
$$

In [12]:
class GCLayer(object):
    def __init__(self, input_dim, output_dim):
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.W = glorot_init(output_dim, input_dim)
        self.W_grad = np.zeros(self.W.shape)
        self.b = np.ones((output_dim, 1))
        self.b_grad = np.zeros(self.b.shape)
        
        
    def relu(self, x):
        return np.vectorize(lambda i : i if i > 0 else 0)(x)
    
    
    def relu_derivative(self, x):
        return (x > 0) * 1
    
    
    '''
    inputs:
    G (nx.Graph)   Normalized Laplacian matrix for a static graph.
                   Dimensions: N x N where N is the number of nodes.
    x (np.ndarray) Embedding matrix
                   Dimensions: N x F where F is the number of features.
    '''
    def __call__(self, G, x):
        # (nodes x nodes), (nodes x features), so need to transpose
        # before taking linear combination
        self.i = x # (nxf)
        self.X = (G @ x).T # (n,n) x (n,f) -> (n,f).T -> (f,n)
        self.z = self.W @ self.X + self.b # (h,f) x (f,n) + (h,1) -> (h,n). Broadcast bias vector.
        self.a = self.relu(self.z) # (h,n), where n is number of samples/nodes
        
        # print('GC Layer')
        # print(f'x.shape: {x.shape}')
        # print(f'X.shape: {self.X.shape}')
        # print(f'W.shape: {self.W.shape}')
        # print(f'b.shape: {self.b.shape}')
        # print(f'z.shape: {self.z.shape}')
        # print(f'a.shape: {self.a.shape}')
        
        # transpose so can multiply by adjacency matrix in next layer
        return self.a.T # (n,h)
    
    
    def backward(self, error):
        batch_size = self.X.shape[1] # batch size
        self.W_grad += (error @ self.X.T)/batch_size # (h,n) x (n,f) -> (h,f) which matches W.shape 
       
        expected_grad = np.average(error, axis=1, weights=[batch_size]*error[0]) # expected gradient
        expected_grad = expected_grad[:, np.newaxis] # add back column dim of 1 to match b_grad shape
        
        self.b_grad += expected_grad # (h,n)
        
        print(f'self.W.T: {self.W.T.shape}')
        print(f'error: {error.shape}')
        print(f'self.z: {self.z.shape}')
        
        return self.W.T @ error * self.relu_derivative(self.z)
    

### Linear Layer

In [13]:
class Linear(object):
    def __init__(self, input_dim, output_dim):
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.W = glorot_init(output_dim, input_dim)
        self.W_grad = np.zeros(self.W.shape)
        self.b = np.ones((self.output_dim, 1))
        self.b_grad = np.zeros(self.b.shape)
        
        
    def relu(self, x):
        return np.vectorize(lambda i : i if i > 0 else 0)(x)
    
    
    def relu_derivative(self, x):
        return (x > 0) * 1
    

    '''
    inputs:
    x (np.ndarray) Inputs to this layer
    
    outputs:
    a (np.ndarray) Output activations
    '''
    def __call__(self, x):    
        self.x = x # (f,n)
        self.z = self.W @ x + self.b # (h,f) x (f,n) + (h,1). Broadcast bias vector.
        self.a = self.relu(self.z)   # (h,n)
        
        # print('Linear layer')
        # print(f'x.shape: {x.shape}')
        # print(f'W.shape: {self.W.shape}')
        # print(f'b.shape: {self.b.shape}')
        # print(f'z.shape: {self.z.shape}')
        
        return self.a.T # (h,n)
    
    
    '''
    inputs:
    error (np.ndarray) Error signal of shape (W.out_dim, batch_size) from subsequent layer
    
    outputs:
    
    '''
    def backward(self, error):
        batch_size = error.shape[1]
        self.W_grad += (error @ self.x.T) / batch_size # (h,n) x (n,f)
        self.b_grad += (np.sum(error, axis=1)) / batch_size # (h,n)
        return self.W.T @ np.multiply(np.array(error), np.array(self.relu_derivative(self.z))) # (f,h) x (h,n) * (h,n)
        # (16,34) and (3,34)
        

### Graph Convolutional Network

In [14]:
class GCN(object):
    def __init__(self, graph, num_classes):
        self.G = graph
        self.nodes = self.G.shape[0]
        self.embedding = np.eye(self.nodes)
        self.l0 = GCLayer(self.nodes, 16)
        self.l1 = GCLayer(16, 16)
        self.l2 = Linear(16, num_classes)
        self.parameters = [self.l0, self.l1, self.l2]
        
        
    def softmax(self, x):
        exps = np.exp(x - np.max(x))
        return exps / np.sum(exps)
        
    
    def __call__(self, x):
        a0 = self.l0(self.G, x)
        a1 = self.l1(self.G, a0).T
        a2 = self.l2(a1)
        return self.softmax(a2)
    
    
    def backward(self, x):
        # Transpose errors from (34,3) -> (3,34) because linear weights are (16,34), but transposed for BP
        # so computation must be (labels, batch_size) x (batch_size, hidden_dim) to get error @ x.T
        d2 = self.l2.backward(x.T)
        print(f'd2.shape: {d2.shape}')
        d1 = self.l1.backward(d2)
        print(f'd1.shape: {d1.shape}')
        d0 = self.l0.backwards(d1)
        print(f'd0.shape: {d0.shape}')
        

### Loss function

In [15]:
def cross_ent(predictions, targets):
    N = predictions.shape[0]
    targets_ = np.squeeze(np.asarray(targets))
    predictions_ = np.squeeze(np.asarray(predictions))
    ce = -np.sum(targets_*np.log(predictions_))/N
    return ce

### Training loop

In [16]:
def train(model, loss, epochs, features, labels, opt):
    for e in range(epochs):
        output = model(features)
        loss = loss(output, labels)
        deriv_loss = output - labels
        
        # print(f'loss: {loss}\n{loss.shape}')
        # print(f'loss_: {deriv_loss}\n{deriv_loss.shape}')
        
        model.backward(deriv_loss)
        opt.step()
        opt.zero_gradients()
        
        print(f'epoch {e} loss: {loss.mean()}')

### Hyperparameters

In [17]:
epochs = 1
lr = 0.1

In [18]:
features = np.eye(G.number_of_nodes())
model = GCN(A_hat, num_classes)
opt = GradientDescent(model.parameters, lr)
train(model, cross_ent, epochs, features, labels, opt)

d2.shape: (16, 34)
self.W.T: (16, 16)
error: (16, 34)
self.z: (16, 34)


ValueError: shapes (16,34) and (16,34) not aligned: 34 (dim 1) != 16 (dim 0)

### Common errors

1. **ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 34 is different from 3)**

**Solution:**
https://stackoverflow.com/a/40035266/3158028

Also was accidentally transposing the Hadamard product which resulted in (16,3)x(34,3)

2. **ValueError: non-broadcastable output operand with shape (16,1) doesn't match the broadcast shape (16,34)**

**Solution:**
Must average the errors across the batch dimension so can get a vector instead of (16,34).

3. **ValueError: non-broadcastable output operand with shape (16,1) doesn't match the broadcast shape (16,16)**

Tried `error = error[:, np.newaxis]`, but this added an extra dimension making error a `(16, 1, 34)` instead of a `(16, 34)`. Applied `[:, np.newaxis]` to error after summing. Summing removed the second dimension, so instead of being `(16,1)` it was just `(16,)`.

4. **ValueError: shapes (16,34) and (16,34) not aligned: 34 (dim 1) != 16 (dim 0)**

